#!/usr/bin/env sh

docker pull ubuntu:22.04
docker run --rm -t --platform linux/amd64 --network host --name builder -d ubuntu:22.04

docker cp ./bin builder:/home/bin
docker cp ./catboost builder:/home/catboost

docker exec builder apt update
docker exec builder apt -y install python3
docker exec builder apt -y install cmake
docker exec builder apt -y install ninja-build
docker exec builder apt -y install clang
docker exec builder apt -y install lld
docker exec builder apt -y install openssl 
docker exec builder apt -y install libssl-dev
docker exec builder apt -y install perl
docker exec builder apt -y install maven
docker exec builder apt -y install swig

docker exec builder apt -y install python3-pip
docker exec builder pip3 install conan 

docker exec -w /home/catboost/catboost/jvm-packages/catboost4j-prediction/ builder mvn compile -f pom.xml

docker cp builder:/home/catboost/catboost/jvm-packages/catboost4j-prediction/target/classes/linux-x86_64/lib/libcatboost4j-prediction.so ./libcatboost4j-prediction.so
